networks:
  auth-network:
    driver: bridge

services:
  auth-service:
    build:
      context: .
      dockerfile: src/AuthService.Api/Dockerfile
    container_name: auth-service
    ports:
      - 5000:8080
    networks:
      - auth-network
    environment:
      ConnectionStrings:DatabaseConnection: Server=postgres-db;Port=5432;Database=auth-service;User Id=postgres;Password=postgres
      ConnectionStrings:RedisConnection: redis-cache

  postgres-db:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - auth-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-service

  redis-cache:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - auth-network
