services:
  auth-service:
    environment:
      ConnectionStrings:DatabaseConnection: Server=postgres-db;Port=5432;Database=auth-service;User Id=postgres;Password=postgres
      ConnectionStrings:RedisConnection: redis-cache
  
  postgres-db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-service

  smtp-server:
    image: jijiechen/papercut
    container_name: smtp-papercut
    ports:
      - 25:25
      - 37408:37408
    networks:
      - auth-network